import { days } from "./parse";
import { emptyCells } from "./stations";
import type { Assignment, WeekRoster } from "./types";
import { weekTitle } from "./dates";

type RawCells = Record<string, [string, string, string, string, string]>;
type RawLeave = Record<string, [string, string, string, string, string]>;

function hydrate(
  monday: string,
  notes: string,
  holidays: number[],
  raw: RawCells,
  leave: RawLeave = {},
  title?: string,
): WeekRoster {
  const cells = emptyCells();
  for (const [id, tuple] of Object.entries(raw)) {
    cells[id] = days(tuple[0], tuple[1], tuple[2], tuple[3], tuple[4]);
  }
  const leaveMap: Record<string, string[]> = {};
  for (const [id, tuple] of Object.entries(leave)) {
    leaveMap[id] = [...tuple];
  }
  return {
    monday,
    title: title ?? weekTitle(monday),
    notes,
    cells,
    leave: leaveMap,
    holidays,
  };
}

const WEEK_2026_06_01 = hydrate(
  "2026-06-01",
  "King's Birthday Monday. Cara IVF on the holiday. PVT 7pm still in use this week.",
  [0],
  {
    early: ["", "WG", "GL", "CS", "AW"],
    pro1: ["CS:IVF", "GL", "CS", "CS", "GL"],
    pro2: ["", "SG", "RP", "SG", "CS"],
    pro3: ["", "RP", "KAH", "KAH", "KAH"],
    val: ["", "GL+AW", "CS", "CS", "GL+AW"],
    pvt_err: ["", "KAH", "JD", "VM", "AD"],
    c513: ["", "WG+MW", "WG+MW", "WG+DM", "WG+DM"],
    alinity: ["", "AD", "AD", "AD", "LO"],
    pvt_am: ["", "AV:am+SM", "AV:am+SM+DM", "VM:am+SM+LO", "VM+LO"],
    pvt_pm: ["", "DM", "", "", "SM"],
    epp: ["", "VM:Animals", "VM", "AL", "AL"],
    epp1: ["", "SPM", "MW", "SPM", "GL+AW"],
    epp2: ["", "AW", "TW", "AW", "TW"],
    send: ["", "LO", "LO", "RP", "RP"],
    immuno_sci: ["", "TW", "TW", "TW", "TW:all day"],
    immuno_am: ["", "JD+SS", "SS", "JD", "JD+SS"],
    admin: ["", "CS:pm", "GL:Sendaways project", "GL:pm Sendaways project", ""],
    cobas_n1: ["", "CS", "AW", "MW", "SM"],
    cobas_n2: ["", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["", "AL:5pm", "AL:5pm", "SS", "AD"],
    pvt9: ["", "DM", "SH", "SH", "SH"],
    pvt7: ["", "LO", "LO", "LO", "LO"],
  },
);

const WEEK_2026_06_08 = hydrate(
  "2026-06-08",
  "",
  [],
  {
    early: ["JD", "WG", "GL", "AW", "AW"],
    pro1: ["CS", "GL", "CS", "WG", "GL"],
    pro2: ["SM", "SM", "SM", "KAH", "KAH"],
    pro3: ["AD", "AD", "AD", "AD", "CS"],
    val: ["CS:am+GL:pm+AW:pm", "GL+AW", "CS", "WG", "GL+AW"],
    pvt_err: ["RP", "CS", "JD", "CS:pm+GO:pm", "AD"],
    c513: ["MW+JD", "MW+WG", "DM+WG", "DM+RP:PM", "DM+WG"],
    alinity: ["DM", "AV:am+DM:pm", "AV:am+GL:pm", "AL", "AL"],
    pvt_am: ["AL", "SG+RP", "RP+KAH", "SG+VM", "RP"],
    pvt_pm: ["KAH+VM:pm", "KAH", "", "GL", "SM"],
    epp: ["LO+VM:start", "LO:Animals", "LO", "LO+AW:start", "LO"],
    epp1: ["SPM", "SPM", "MW", "AW", "AW"],
    epp2: ["AW", "AW", "TW", "TW", "TW"],
    send: ["SG", "VM", "VM", "VM:PVT help", "VM"],
    immuno_sci: ["TW", "TW", "TW+MW", "TW", "TW:all day"],
    immuno_am: ["SS", "SS+JD", "SS:am", "JD+SS:pm", "JD+SS"],
    admin: ["WG:pm+CS:pm+AW:IQM", "", "GL:am+AW:pm", "AW+CS:Roche QC with Erin", ""],
    cobas_n1: ["WG", "CS", "AW", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["GL", "AL:5pm", "AL:5pm", "SS", "AD"],
    pvt9: ["KAH", "DM", "SH", "SH", "SH"],
    pvt7: ["LO", "LO", "LO", "LO", "LO"],
  },
  {
    VM: ["Hosp appt 10:30", "", "", "", ""],
    SM: ["", "", "", "Leave", ""],
  },
);

const WEEK_2026_06_15 = hydrate(
  "2026-06-15",
  "Trial of evening roster change begins. PVT 7pm no longer exists.",
  [],
  {
    early: ["JD", "WG", "GL", "CS", "JD"],
    pro1: ["WG", "WG", "CS", "WG", "WG"],
    pro2: ["AD", "AD", "AD", "AD", "VM"],
    pro3: ["SG", "SG", "GL", "CS", "GL"],
    val: ["WG:am+GL:pm+AW", "WG", "CS", "WG", "WG"],
    pvt_err: ["RP", "KAH", "JD", "GL", "SM"],
    c513: ["MW+VM", "MW+RP", "DM+RP", "DM+RP", "DM+RP"],
    alinity: ["LO", "GL", "AV:am+WG:pm", "SS", "AL"],
    pvt_am: ["DM+CS:am", "VM", "VM+LO", "LO+VM", "LO"],
    pvt_pm: ["SS", "DM+JD", "", "", "AD"],
    epp: ["SM", "SM:Animals+AW", "SM", "SM", "SS"],
    epp1: ["SPM", "SPM", "SPM", "SPM", "AW"],
    epp2: ["TW", "AW", "AW", "AW", "TW"],
    send: ["AL", "AV:am+LO:pm", "KAH", "KAH", "KAH"],
    immuno_sci: ["TW", "TW", "TW+MW", "TW", "CS:am"],
    immuno_am: ["JD", "JD:am+SS", "SS", "JD", "JD"],
    admin: ["CS:pm+WG:pm", "CS:pm", "", "", ""],
    cobas_n1: ["GL+AW:1-9", "CS", "WG", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["KAH", "LO", "AL:5pm", "AL:5pm", "AD"],
    pvt9: ["SS", "DM", "SH", "SH", "SH"],
  },
  {
    GO: ["", "", "", "AKL", "AKL"],
    TW: ["", "", "", "", "Leave"],
  },
);

const WEEK_2026_06_22 = hydrate(
  "2026-06-22",
  "Week #2 roster change trial. Tea room duty.",
  [],
  {
    early: ["JD", "WG", "GL", "CS", "JD"],
    pro1: ["SM", "SM", "CS+GO", "CS+GO", "WG"],
    pro2: ["LO", "AL", "LO", "VM", "VM"],
    pro3: ["VM", "VM", "VM", "LO", "AD"],
    val: ["SM:am+GL:pm+AW", "SM", "CS+GO:am", "CS+GO:am", "WG"],
    pvt_err: ["AD", "KAH", "WG", "GL:late?", "LO"],
    c513: ["DM+JD", "JD+AV:am", "DM+AV:am", "DM+AD", "DM+JD"],
    alinity: ["CS", "GL", "GL", "WG", "GL"],
    pvt_am: ["AL+WG", "SG+LO", "SM+AD", "KAH", "KAH+CS:am"],
    pvt_pm: ["KAH", "DM", "JD", "SM", "SS:pm"],
    epp: ["SG", "SS:Animals", "SS", "SG", "AW"],
    epp1: ["SPM", "SPM", "SPM", "AW", "AW"],
    epp2: ["AW", "AW", "AW", "TW", "TW"],
    send: ["WG:PVT am", "WG:am+AD:pm", "KAH", "JD", "AL"],
    immuno_sci: ["TW", "TW", "TW", "TW", "TW:all day"],
    immuno_am: ["MW:2pm+SS:pm", "MW:2pm", "MW:2pm", "SS", "SS:am"],
    admin: ["SM:pm", "CS:pm+WG:pm", "", "", ""],
    cobas_n1: ["GL", "CS", "WG", "SM", "MW:5pm"],
    cobas_n2: ["AD", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["KAH", "LO", "AL:5pm", "AL:5pm", "AD"],
    pvt9: ["SS", "DM", "SH", "SH", "SH"],
  },
  {
    RP: ["Leave", "Leave", "Leave", "Leave", "Leave"],
    SM: ["", "", "", "", "Leave"],
  },
);

const WEEK_2026_06_29 = hydrate(
  "2026-06-29",
  "Week #3 roster change trial. Lunch and learn Tuesday 30 June — let Anne know who wants to go.",
  [],
  {
    early: ["AW", "WG", "GL", "CS", "AW"],
    pro1: ["MW", "MW", "MW", "WG", "WG"],
    pro2: ["AW:am+RP:pm", "VM", "KAH+CS:cover", "KAH", "KAH"],
    pro3: ["DM+CS", "SM", "SM", "DM+CS", "DM+CS"],
    val: ["MW:am+GL:pm+AW", "MW+WG:pm", "MW+WG:pm", "WG", "WG"],
    pvt_err: ["KAH", "KAH", "JD", "GL", "SM"],
    c513: ["SM+DM", "JD+SG", "VM+LO", "VM+LO", "VM+LO"],
    alinity: ["WG", "LO", "SS", "SS", "SS"],
    pvt_am: ["AL+LO", "AL+AV:am", "DM+AV:am", "SM", "AL+AD"],
    pvt_pm: ["SS", "AD+DM", "CS:pm", "JD", "LO"],
    epp: ["SG", "GL:Animals", "GL", "SG+AW:PEG", "GL"],
    epp1: ["SPM", "GL+AW", "GL+AW", "SPM", "GL+AW"],
    epp2: ["AW", "AW", "AW", "AW", "TW"],
    send: ["LO:PVT am", "RP", "RP", "RP", "RP"],
    immuno_sci: ["TW", "TW", "TW", "TW", "TW:all day"],
    immuno_am: ["AD", "SS", "AD", "AD", "JD"],
    admin: ["", "STOCKTAKE", "KAH CPD 9am+CS:am", "", ""],
    cobas_n1: ["GL", "WG", "WG", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["KAH", "AD", "AL:5pm", "AL", "LO"],
    pvt9: ["SS", "DM", "SH", "JD", "SS"],
  },
  {
    JD: ["Leave", "", "", "", ""],
    VM: ["Leave", "", "", "", ""],
    CS: ["", "IATA", "", "", ""],
    SH: ["", "", "", "Leave", "Leave"],
  },
);

const WEEK_2026_07_06 = hydrate(
  "2026-07-06",
  "Welcome Ally Marshall, AUT student. Friday is Matariki — Verna in for IVF samples only.",
  [4],
  {
    early: ["JD", "WG", "GL", "WG", "VM:IVF samples"],
    pro1: ["WG", "WG", "SM", "WG", ""],
    pro2: ["LO", "VM", "LO", "LO", ""],
    pro3: ["MW:am+KAH:pm", "JD", "MW:am+DM+WG:pm", "SM+DM", ""],
    val: ["WG", "WG", "SM", "WG", ""],
    pvt_err: ["RP", "KAH", "JD", "GL", ""],
    c513: ["SM+AD", "AD+SM", "VM+GO:am", "VM+GO:am", ""],
    alinity: ["VM", "GL", "KAH", "KAH", ""],
    pvt_am: ["DM+AL+AY", "RP+AY", "AV:am+GL:am+AY:am", "RP+AY", ""],
    pvt_pm: ["GL:pm+AY:pm", "DM", "RP+DM:pm", "JD", ""],
    epp: ["AW", "LO:Animals+AW", "AW", "SS", ""],
    epp1: ["AW", "SPM", "AW", "TW", ""],
    epp2: ["TW", "AW", "TW", "AW", ""],
    send: ["AD:c513 am", "AL", "AD", "AD", ""],
    immuno_sci: ["TW", "MW", "TW", "TW", ""],
    immuno_am: ["JD", "SS", "SS", "SS:EPP", ""],
    admin: ["GL:H&S+AY", "", "", "", ""],
    cobas_n1: ["GL", "TW:5pm", "WG", "MW", ""],
    cobas_n2: ["RP", "KAH", "JD", "GL", ""],
    send_eve: ["KAH", "AV:4:30pm", "AL:5pm", "JD", ""],
    pvt9: ["SS", "DM", "RP", "AW", ""],
  },
  {
    SG: ["Leave", "Leave", "", "Leave", ""],
    CS: ["Leave", "Leave", "Leave", "Leave", ""],
    GL: ["", "", "pm", "", ""],
    SH: ["", "", "Leave", "Leave", ""],
    AL: ["", "", "", "Leave", ""],
  },
);

const WEEK_2026_07_13 = hydrate(
  "2026-07-13",
  "Week #5 post roster change — speak up if problems.",
  [],
  {
    early: ["CS", "WG", "GL", "CS", "AW"],
    pro1: ["SM", "WG", "CS", "WG", "WG"],
    pro2: ["MW:am+GL:pm", "MW:am+CS:pm", "MW:am+KAH:pm", "AW", "AW"],
    pro3: ["CS", "RP", "RP+DM", "RP+DM", "RP+DM"],
    val: ["SM", "WG", "CS", "WG", "WG"],
    pvt_err: ["RP", "KAH", "WG", "GL", "SM"],
    c513: ["WG", "SM+LO", "SM+GO:am", "KAH+GO:am", "KAH"],
    alinity: ["DM", "AD", "AD", "CS", "CS"],
    pvt_am: ["AD+AY", "GL+AY+SS", "GL+AY+AV:am", "AD", "GL+AY"],
    pvt_pm: ["KAH", "DM", "JD", "SM", "LO+AD"],
    epp: ["SS:IMF", "AL:Animals+AW", "AW+SS:IMF", "JD", "AL"],
    epp1: ["SPM", "MW", "MW", "AW", "TW"],
    epp2: ["TW", "AW", "AW", "TW", "AW"],
    send: ["LO", "AL", "LO", "LO", "SS"],
    immuno_sci: ["TW:12-5pm", "TW", "TW", "TW", "TW:all day"],
    immuno_am: ["JD:EPP", "JD", "SS", "SS", "JD"],
    cobas_n1: ["GL", "CS", "WG", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["KAH", "AV:4:30pm", "AL:5pm", "AL", "LO"],
    pvt9: ["SS", "DM", "KAH", "SM", "AD"],
  },
  {
    SG: ["Leave", "Leave", "", "Leave", ""],
    AL: ["Leave", "", "", "", ""],
    AW: ["Leave", "", "", "", ""],
    GO: ["Leave", "", "", "", ""],
    VM: ["SKL", "SKL", "SKL", "SKL", "SKL"],
    GL: ["", "pm", "pm", "", "pm"],
    SH: ["", "", "Leave", "Leave", "Leave"],
    AY: ["", "", "", "Leave", ""],
  },
);

const WEEK_2026_07_20 = hydrate(
  "2026-07-20",
  "",
  [],
  {
    early: ["CS", "WG", "GL", "CS", "AW"],
    pro1: ["CS", "SM", "SM", "CS", "CS"],
    pro2: ["WG", "WG", "LO", "WG", "WG"],
    pro3: ["DM+CS", "MW:am+CS:pm", "DM+CS", "DM+CS", "DM+CS"],
    val: ["CS:am+GL:pm", "SM", "SM", "CS", "CS"],
    pvt_err: ["RP", "KAH", "CS:pm+GO:pm", "GL+GO:pm", "SM"],
    c513: ["AD", "LO", "AD", "AD", "AD"],
    alinity: ["SM+AY", "RP+AY", "MW:am+AY+RP:pm", "RP+AY", "RP"],
    pvt_am: ["AL", "GL:am+SG", "GL:am", "LO", "GL:am+AL"],
    pvt_pm: ["SS+KAH", "DM", "KAH+SS:pm", "SG", "LO"],
    epp: ["LO", "AL:Animals+AW", "AW", "SM", "AW"],
    epp1: ["SPM", "MW", "AW", "SPM", "AW"],
    epp2: ["AW", "AW", "TW", "TW", "TW"],
    send: ["SG:PVT am", "AV:am+AD:pm", "AV:am+WG:pm", "KAH", "KAH"],
    immuno_sci: ["TW", "TW", "TW", "TW", "TW:all day"],
    immuno_am: ["MW:2pm", "SS", "SS", "SS", "SS"],
    cobas_n1: ["GL", "CS", "WG", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "KAH", "GL", "SG:1630"],
    send_eve: ["KAH", "AD", "AL:5pm", "AL", "LO"],
    pvt9: ["SS", "DM", "RP", "SG", "AV:5pm"],
  },
  {
    JD: ["Leave", "Leave", "Leave", "Leave", "Leave"],
    AW: ["am (in at 1pm)", "", "", "", ""],
    VM: ["SKL", "SKL", "SKL", "SKL", "SKL"],
    GL: ["", "pm", "pm", "", "pm"],
    SH: ["", "", "Leave", "Leave", "Leave"],
    AY: ["", "", "", "", "Leave"],
  },
);

const WEEK_2026_07_27 = hydrate(
  "2026-07-27",
  "",
  [],
  {
    early: ["AW", "WG", "GL", "CS", "AW"],
    pro1: ["WG", "GL", "CS", "AW", "CS"],
    pro2: ["CS", "AV:am+AD:pm", "AV:am+AD:pm", "DM+RP", "DM+RP"],
    pro3: ["DM", "WG", "DM", "WG", "AL"],
    val: ["WG", "GL:am+AW+CS:pm", "CS", "AW", "CS"],
    pvt_err: ["RP", "KAH", "RP", "SG", "GL"],
    c513: ["AL+AD", "LO+RP", "LO+AD:am", "KAH", "GO:am+SM:pm"],
    alinity: ["SM+AY", "SM+AY", "SM+AY", "SM+AY", "WG"],
    pvt_am: ["SG", "SG+AL", "GL:am", "AD", "AD"],
    pvt_pm: ["KAH", "DM", "WG+KAH", "GL", "LO"],
    epp: ["VM", "VM:Animals", "VM", "VM", "AW"],
    epp1: ["MW", "SPM", "AW", "SPM", "AW"],
    epp2: ["AW", "AW", "TW", "TW", "TW"],
    send: ["LO:PVT", "SS", "SS", "LO", "KAH"],
    immuno_sci: ["TW", "TW", "TW", "TW", "TW:all day"],
    immuno_am: ["MW+SS:pm", "MW", "MW", "SS", "SS"],
    admin: ["GL:pm", "", "", "STOCKTAKE CS", ""],
    cobas_n1: ["GL", "CS", "WG", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "RP", "GL", "SG:1630"],
    send_eve: ["KAH", "AD", "AL:5pm", "AL:5pm", "LO"],
    pvt9: ["SS", "DM", "KAH", "SG", "GL"],
  },
  {
    JD: ["Leave", "Leave", "Leave", "Leave", "Leave"],
    GL: ["", "pm", "pm", "", ""],
    SH: ["", "", "Leave", "Leave", "Leave"],
    AY: ["", "", "", "", "Leave"],
    VM: ["", "", "", "", "Leave"],
  },
);

const WEEK_2026_08_03 = hydrate(
  "2026-08-03",
  "",
  [],
  {
    early: ["JD", "WG", "GL", "AW", "JD"],
    pro1: ["MW", "MW", "MW", "SM", "AW"],
    pro2: ["SG", "RP", "DM+GL", "DM+GL:pm", "DM+GL:pm"],
    pro3: ["DM", "SG", "LO", "LO", "LO"],
    val: ["MW:am+GL:pm", "MW:am+SM:pm", "MW:am+WG:pm", "SM", "AW:am+SM:pm"],
    pvt_err: ["KAH", "AD", "JD", "AD", "LO"],
    c513: ["WG+AY", "WG+AY", "SM+AW", "RP+AY", "AY+RP"],
    alinity: ["AL", "AV:am+KAH:pm", "SS", "SS", "SS"],
    pvt_am: ["LO+SM", "AL+LO", "KAH+RP:am", "KAH+SG", "KAH+AL"],
    pvt_pm: ["SS", "DM", "AD:2pm", "", ""],
    epp: ["JD", "JD:Animals", "AV:am+RP:pm", "JD", "JD"],
    epp1: ["SPM", "GL", "GL", "SPM", "TW"],
    epp2: ["AW", "AW", "AW", "AW", "AW"],
    send: ["VM", "VM", "VM", "VM", "VM"],
    immuno_sci: ["TW+AD", "TW", "TW", "TW", "TW:all day+AD"],
    immuno_am: ["AD:all day", "SS", "AD:2pm", "AD:2pm", "AD:all day"],
    admin: ["SM:pm+RP", "GL", "", "", "GL:am"],
    cobas_n1: ["GL", "SM", "WG", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["KAH", "AD", "AL:5pm", "AL", "LO"],
    pvt9: ["SS", "DM", "SH", "SH", "SH"],
  },
  {
    CS: ["Leave", "Leave", "Leave", "Leave", "Leave"],
    AY: ["", "", "Leave", "", ""],
    WG: ["", "", "", "Leave", "Leave"],
  },
);

const WEEK_2026_08_10 = hydrate(
  "2026-08-10",
  "",
  [],
  {
    early: ["JD", "AW", "GL", "CS", "JD"],
    pro1: ["SM", "GL", "GL", "WG", "GL"],
    pro2: ["MW:am+RP:pm", "SM", "SM", "SM", "AL:am"],
    pro3: ["LO", "LO", "VM", "VM", "VM"],
    val: ["SM", "GL+AW", "GL+AW", "WG", "GL+AW"],
    pvt_err: ["GL", "AD", "WG", "GL", "LO"],
    c513: ["JD+AY", "JD+AY", "CS", "JD+AY", "WG+AY"],
    alinity: ["VM", "RP", "LO", "LO", "JD"],
    pvt_am: ["AL", "MW+AL", "MW+KAH", "SG+KAH", "KAH"],
    pvt_pm: ["SS+KAH", "KAH", "SS:pm", "", "SM"],
    epp: ["AW", "AV:Animals+SS:IMF pm", "AV+JD:pm", "CS", "CS"],
    epp1: ["AW", "MW", "MW", "SPM", "AW"],
    epp2: ["TW", "AW", "AW", "AW", "TW"],
    send: ["SG", "SG", "RP", "RP", "RP"],
    immuno_sci: ["TW", "TW", "TW", "TW", "TW:all day"],
    immuno_am: ["AD:all day", "SS:am", "SS", "SS", "SS"],
    admin: ["", "CS:pm", "", "", ""],
    cobas_n1: ["GL", "CS", "WG", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["KAH", "AD", "AL:5pm", "AL", "LO"],
    pvt9: ["SS", "GO", "SH", "SH", "SH"],
  },
  {
    WG: ["Leave", "Leave", "", "", ""],
    DM: ["Leave", "Leave", "Leave", "Leave", "Leave"],
    CS: ["Leave", "Leave", "", "", ""],
    AD: ["", "", "Leave", "Leave", "Leave"],
    AY: ["", "", "Leave", "", ""],
    VM: ["", "Leave", "", "", ""],
    AL: ["", "", "", "", "pm"],
  },
);

const WEEK_2026_08_17 = hydrate(
  "2026-08-17",
  "Tearoom duty — everyone.",
  [],
  {
    early: ["AW", "WG", "GL", "CS", "JD"],
    pro1: ["MW", "GL", "GL", "SM", "GL"],
    pro2: ["SG", "SG", "KAH", "KAH", "KAH"],
    pro3: ["CS", "VM:am+AD:pm", "CS+AY", "CS+AY", "CS:1pm+AY+JD:1pm"],
    val: ["MW+GL:pm", "GL", "GL", "SM", "GL"],
    pvt_err: ["KAH", "KAH", "JD", "WG:pm", "SM"],
    c513: ["VM+AY", "WG+SS", "MW:am+WG:pm", "SS+JD", "SS+WG"],
    alinity: ["WG", "RP", "RP", "RP", "RP"],
    pvt_am: ["DM", "SM+LO", "DM+SM", "DM+SG", "DM"],
    pvt_pm: ["SS+RP", "DM", "SS", "AD", "LO"],
    epp: ["AW:am+JD:IMF", "AV:am Animals+VM:IMF", "VM", "VM", "VM"],
    epp1: ["SPM", "MW", "MW", "SPM", "TW"],
    epp2: ["AW", "AW", "AW", "TW", "PATH"],
    send: ["AL", "AL", "LO", "LO", "AL"],
    immuno_sci: ["TW", "TW+MW", "TW+AD", "TW", "TW:all day+AD"],
    immuno_am: ["JD", "JD", "SS:2pm", "AD:2pm", "JD:1pm"],
    admin: ["", "CS", "", "GL:pm", ""],
    cobas_n1: ["GL", "CS", "WG", "WG", "SM"],
    cobas_n2: ["RP", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["KAH", "AD", "AL:5pm", "AL", "LO"],
    pvt9: ["SS", "DM", "SH", "SH", "SH"],
  },
  {
    AD: ["Leave", "", "", "", ""],
    LO: ["Leave", "", "", "", ""],
    AY: ["", "Leave", "", "", ""],
    AW: ["", "", "", "CL", "Leave"],
    MW: ["", "", "", "Leave", ""],
    CS: ["", "", "", "", "1pm"],
  },
);

const WEEK_2026_08_24 = hydrate(
  "2026-08-24",
  "",
  [],
  {
    early: ["JD", "WG", "GL", "CS", "JD"],
    pro1: ["WG", "WG", "SM", "SM", "CS"],
    pro2: ["VM+GL:pm nLo", "VM", "AV:am+WG:pm", "CS", "GL"],
    pro3: ["JD", "SM", "CS", "WG", "WG"],
    val: ["WG", "WG", "SM", "SM", "CS"],
    pvt_err: ["KAH", "AD", "JD", "GL", "SM"],
    c513: ["CS", "GL+SS", "GL+SS", "SS", "SS"],
    alinity: ["SG", "SG", "KAH", "SG", "AL"],
    pvt_am: ["DM", "LO+AL", "VM", "KAH", "KAH"],
    pvt_pm: ["SS+RP", "DM", "AD:2pm", "JD:2pm", "LO"],
    epp: ["SM", "RP:Animals", "RP", "RP", "RP"],
    epp1: ["AW", "GL", "GL", "AW", "GL"],
    epp2: ["TW", "AW", "AW", "TW", "AW"],
    send: ["LO", "AV:am+KAH:pm", "LO+DM", "LO+DM", "DM+JD"],
    immuno_sci: ["TW", "MW", "TW+AD:2pm", "TW+AD", "TW:all day"],
    immuno_am: ["AD:2pm", "TW", "MW", "JD:2pm", "AD:2pm"],
    admin: ["", "CS:pm", "", "", ""],
    cobas_n1: ["GL", "CS", "WG", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["KAH", "AD", "AL:5pm", "AL", "LO"],
    pvt9: ["SS", "DM", "SH", "SH", "SH"],
  },
  {
    AL: ["Leave", "", "", "", ""],
    MW: ["Leave", "", "", "", ""],
    AY: ["Leave", "Leave", "Leave", "Leave", "Leave"],
    VM: ["", "", "", "Leave", "Leave"],
  },
);

const WEEK_2026_08_31 = hydrate(
  "2026-08-31",
  "Stocktake Monday.",
  [],
  {
    early: ["JD", "WG", "GL", "CS", "JD"],
    pro1: ["MW", "WG", "MW", "WG", "WG"],
    pro2: ["AL", "AL", "VM", "VM", "AL"],
    pro3: ["SM", "SG", "GL", "SG", "GL"],
    val: ["MW:am+GL:pm", "WG", "MW+WG:pm", "WG", "WG"],
    pvt_err: ["SG", "KAH", "JD", "GL", "LO"],
    c513: ["LO", "LO", "LO", "LO", "VM"],
    alinity: ["GO:am+RP:pm", "AV:am+AD:pm", "AV:am+AD:pm", "SM", "CS"],
    pvt_am: ["WG", "VM+SM", "SM", "RP", "RP"],
    pvt_pm: ["KAH", "DM", "AD", "JD", "SM"],
    epp: ["VM", "GL:Animals", "KAH+AW", "KAH+AW", "KAH+AW"],
    epp1: ["SPM", "GL", "GL", "TW", "GL"],
    epp2: ["AW", "AW", "AW", "AW", "AW"],
    send: ["DM+JD", "RP", "DM+RP", "DM+AD", "DM"],
    immuno_sci: ["TW", "TW+MW", "TW", "TW", "TW:all day+AD"],
    immuno_am: ["AD", "JD:2pm", "AD:2pm", "JD:2pm", "JD:2pm"],
    admin: ["CS:stocktake", "CS:pm", "CS", "CS", ""],
    cobas_n1: ["GL", "CS", "WG", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["KAH", "AD", "AL:5pm", "AL", "LO"],
    pvt9: ["SG", "DM", "SH", "SH", "SH"],
  },
  {
    SS: ["Leave", "Leave", "Leave", "Leave", "Leave"],
    AY: ["Leave", "Leave", "Leave", "Leave", "Leave"],
    GO: ["", "", "Leave", "", ""],
  },
);

const WEEK_2026_09_07 = hydrate(
  "2026-09-07",
  "IANZ audit Monday.",
  [],
  {
    early: ["JD", "WG", "GL", "CS", "JD"],
    pro1: ["CS", "WG", "CS", "CS", "CS"],
    pro2: ["VM", "VM", "VM", "VM", "GL"],
    pro3: ["JD", "GL+AY", "GL", "JD", "JD"],
    val: ["CS", "WG", "CS", "CS", "CS"],
    pvt_err: ["GL", "CS", "WG", "GL", "LO"],
    c513: ["WG+DM", "RP", "RP", "RP", "RP"],
    alinity: ["MW:am+AL:pm", "MW:am+AD:pm", "MW:am", "WG", "WG"],
    pvt_am: ["SG", "AL:am+SG", "KAH", "SG", "AL"],
    pvt_pm: ["KAH+RP", "KAH", "AD", "AD", "SM"],
    epp: ["SM", "AV:am Animals+JD:pm", "AV:am+JD:pm", "SM+KAH", "KAH+AW"],
    epp1: ["SPM", "MW", "MW", "SPM", "AW"],
    epp2: ["AW", "AW", "AW", "AW", "TW"],
    send: ["LO", "LO+DM:pm", "LO+DM", "DM", "DM"],
    immuno_sci: ["TW", "TW", "TW", "TW", "TW:all day"],
    immuno_am: ["AD", "JD:am", "AD:2pm", "AD:2pm", "AD"],
    admin: ["CS:IANZ audit", "", "", "", ""],
    cobas_n1: ["GL", "CS", "WG", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["KAH", "AD", "AL:5pm", "AL", "LO"],
    pvt9: ["AV:4pm", "DM", "SH", "SH", "SH"],
  },
  {
    SS: ["Leave", "Leave", "Leave", "Leave", "Leave"],
    AL: ["am", "pm", "", "", ""],
    AY: ["Leave", "Leave", "CHL", "CHL", "CHL"],
    SM: ["", "Leave", "Leave", "", ""],
    LO: ["", "", "", "Leave", ""],
  },
);

const WEEK_2026_09_14 = hydrate(
  "2026-09-14",
  "",
  [],
  {
    early: ["AW", "WG", "GL", "CS", "AW"],
    pro1: ["SM", "SM", "CS", "WG", "WG"],
    pro2: ["AD", "VM", "AD", "AD", "RP"],
    pro3: ["WG+AY", "WG+AY", "VM", "CS+AY", "CS+AY"],
    val: ["SM", "SM", "CS", "WG", "WG"],
    pvt_err: ["RP", "AD", "WG", "GL", "LO"],
    c513: ["VM", "GL:operator+RP", "GL:operator+RP:am", "RP", "GL:operator"],
    alinity: ["AL", "AL", "LO", "LO", "AL"],
    pvt_am: ["LO", "LO", "AV", "VM+SG", "VM"],
    pvt_pm: ["SG+KAH", "DM", "JD+RP:pm", "", "SM"],
    epp: ["", "SG:Animals", "KAH+SM", "KAH+SM", "KAH"],
    epp1: ["MW", "MW", "SPM", "SPM", "AW"],
    epp2: ["AW", "AW", "AW", "AW", "TW"],
    send: ["DM", "AV:am+KAH:pm", "DM", "DM", "DM"],
    immuno_sci: ["MW:2pm", "MW:2pm", "MW:2pm", "TW", "TW:all day"],
    immuno_am: ["TW:2pm", "TW:2pm", "TW:2pm", "JD:2pm", "JD:2pm"],
    admin: ["CS+GL:pm", "CS:pm", "", "", ""],
    cobas_n1: ["GL", "CS", "WG", "MW", "SM"],
    cobas_n2: ["RP", "KAH", "JD", "GL", "SG:1630"],
    send_eve: ["KAH", "AD", "AL:5pm", "AL", "LO"],
    pvt9: ["SG", "DM", "SH", "SH", "SH"],
  },
  {
    SS: ["Leave", "Leave", "Leave", "Leave", "Leave"],
    JD: ["Leave", "Leave", "", "", ""],
    AY: ["", "", "Leave", "", ""],
    AD: ["", "", "", "", "Leave"],
  },
);

export const ARCHIVE: WeekRoster[] = [
  WEEK_2026_06_01,
  WEEK_2026_06_08,
  WEEK_2026_06_15,
  WEEK_2026_06_22,
  WEEK_2026_06_29,
  WEEK_2026_07_06,
  WEEK_2026_07_13,
  WEEK_2026_07_20,
  WEEK_2026_07_27,
  WEEK_2026_08_03,
  WEEK_2026_08_10,
  WEEK_2026_08_17,
  WEEK_2026_08_24,
  WEEK_2026_08_31,
  WEEK_2026_09_07,
  WEEK_2026_09_14,
];

export function archiveByMonday(): Record<string, WeekRoster> {
  const out: Record<string, WeekRoster> = {};
  for (const w of ARCHIVE) out[w.monday] = structuredClone(w);
  return out;
}

export function cloneWeek(w: WeekRoster, monday: string, title: string): WeekRoster {
  const cells: Record<string, Assignment[][]> = {};
  for (const [id, row] of Object.entries(w.cells)) {
    cells[id] = row.map((c) => c.map((a) => ({ ...a })));
  }
  const leave: Record<string, string[]> = {};
  for (const [id, row] of Object.entries(w.leave)) leave[id] = [...row];
  return { monday, title, notes: "", cells, leave, holidays: [] };
}
