import type { StaffMember } from "./types";

export const STAFF: StaffMember[] = [
  {
    id: "AW",
    firstName: "Anne",
    lastName: "Wilkinson",
    initials: "AW",
    rosterName: "Anne",
    role: "scientist",
    fte: "full",
    color: "#2f6f6a",
    autoAssign: true,
    notes: "Often Friday or Monday early start; EPP 2nd read; validation helper.",
    active: true,
  },
  {
    id: "CS",
    firstName: "Cara",
    lastName: "Scott",
    initials: "CS",
    rosterName: "Cara",
    role: "scientist",
    fte: "full",
    color: "#3d5a80",
    autoAssign: true,
    notes: "Frequent PRO 1 / Thursday early start. Tuesday COBAS N1 evening.",
    active: true,
  },
  {
    id: "WG",
    firstName: "William",
    lastName: "Gouws",
    initials: "WG",
    rosterName: "William",
    role: "scientist",
    fte: "full",
    color: "#6b5344",
    autoAssign: true,
    notes: "Almost always Tuesday early start. Wednesday COBAS N1 evening.",
    active: true,
  },
  {
    id: "GL",
    firstName: "Greg",
    lastName: "Leamon",
    initials: "GL",
    rosterName: "Greg",
    role: "scientist",
    fte: "full",
    color: "#4a6741",
    autoAssign: true,
    notes: "Always Wednesday early start. Monday COBAS N1 and Thursday COBAS N2 evenings.",
    active: true,
  },
  {
    id: "AD",
    firstName: "Alice",
    lastName: "Dony",
    initials: "AD",
    rosterName: "Alice",
    role: "scientist",
    fte: "full",
    color: "#7a4458",
    autoAssign: true,
    active: true,
  },
  {
    id: "SM",
    firstName: "Shezeetha",
    lastName: "Matthews",
    initials: "SM",
    rosterName: "Shezeetha",
    role: "scientist",
    fte: "full",
    color: "#b85c38",
    autoAssign: true,
    notes: "Friday COBAS N1 evening.",
    active: true,
  },
  {
    id: "MW",
    firstName: "Megan",
    lastName: "Winks",
    initials: "MW",
    rosterName: "Megan",
    role: "scientist",
    fte: "part",
    color: "#3f6b8a",
    autoAssign: true,
    notes: "Part-time. Thursday COBAS N1 evening. Covers immunology when Teresa is away.",
    active: true,
  },
  {
    id: "TW",
    firstName: "Teresa",
    lastName: "Wong",
    initials: "TW",
    rosterName: "Teresa",
    role: "scientist",
    fte: "part",
    specialist: "immunology",
    color: "#8a5a2a",
    autoAssign: true,
    notes: "Immunology specialist (Theresa). Friday immunology all day. Rarely on core benches.",
    active: true,
  },
  {
    id: "AL",
    firstName: "Abby",
    lastName: "Luet",
    initials: "AL",
    rosterName: "Abby",
    role: "technician",
    fte: "part",
    color: "#5c6b4a",
    autoAssign: true,
    notes: "Wednesday & Thursday sendaways evening (often 5 pm).",
    active: true,
  },
  {
    id: "SG",
    firstName: "Susanna",
    lastName: "Gin",
    initials: "SG",
    rosterName: "Susanna",
    role: "technician",
    fte: "part",
    color: "#4d6a7a",
    autoAssign: true,
    notes: "Friday COBAS N2 until 16:30.",
    active: true,
  },
  {
    id: "AV",
    firstName: "Amanda",
    lastName: "Vette",
    initials: "AV",
    rosterName: "Amanda",
    role: "technician",
    fte: "part",
    color: "#7a6240",
    autoAssign: true,
    morningsOnly: true,
    notes: "Typically morning only (Alinity / PVT / EPP am).",
    active: true,
  },
  {
    id: "KAH",
    firstName: "Kelly-Anne",
    lastName: "Howard",
    initials: "KAH",
    rosterName: "Kelly-Anne",
    role: "technician",
    fte: "full",
    color: "#5a4e7a",
    autoAssign: true,
    notes: "Tuesday PVT-PM errors + Tuesday COBAS N2. Monday sendaways 9.30 evening.",
    active: true,
  },
  {
    id: "DM",
    firstName: "Daphne",
    lastName: "Moreno",
    initials: "DM",
    rosterName: "Daphne",
    role: "technician",
    fte: "full",
    color: "#6a3f4a",
    autoAssign: true,
    notes: "Tuesday PVT 9 pm evening.",
    active: true,
  },
  {
    id: "VM",
    firstName: "Verna",
    lastName: "Murcott",
    initials: "VM",
    rosterName: "Verna",
    role: "technician",
    fte: "full",
    color: "#3f5c4a",
    autoAssign: true,
    active: true,
  },
  {
    id: "RP",
    firstName: "Rose",
    lastName: "Ploeg",
    initials: "RP",
    rosterName: "Rose",
    role: "technician",
    fte: "full",
    color: "#7a4035",
    autoAssign: true,
    notes: "Monday COBAS N2 evening.",
    active: true,
  },
  {
    id: "SS",
    firstName: "Susie",
    lastName: "Storr",
    initials: "SS",
    rosterName: "Susie",
    role: "technician",
    fte: "full",
    specialist: "immunology",
    color: "#4a5870",
    autoAssign: true,
    notes: "Immunology technician. Monday PVT 9 pm evening.",
    active: true,
  },
  {
    id: "JD",
    firstName: "Jacquie",
    lastName: "Duff",
    initials: "JD",
    rosterName: "Jacquie",
    role: "technician",
    fte: "full",
    color: "#2f4f6a",
    autoAssign: true,
    notes: "Often Monday/Friday early start. Wednesday PVT-PM errors + Wednesday COBAS N2.",
    active: true,
  },
  {
    id: "LO",
    firstName: "Loraine",
    lastName: "",
    initials: "LO",
    rosterName: "Loraine",
    role: "technician",
    fte: "full",
    color: "#5c6a38",
    autoAssign: true,
    notes: "On every supplied roster but not on the original staff list — added from the documents. Friday sendaways evening.",
    active: true,
  },
  {
    id: "SH",
    firstName: "Shamsia",
    lastName: "",
    initials: "SH",
    rosterName: "Shamsia",
    role: "technician",
    fte: "part",
    color: "#5a6570",
    autoAssign: true,
    eveningOnly: true,
    notes: "Evening PVT 9 pm Wednesday–Friday. Not on the day grid.",
    active: true,
  },
  {
    id: "GO",
    firstName: "Gordon",
    lastName: "",
    initials: "GO",
    rosterName: "Gordon",
    role: "casual",
    fte: "part",
    color: "#6a5c48",
    autoAssign: false,
    notes: "Appears occasionally (c513, PVT-PM, Alinity). Not auto-assigned.",
    active: true,
  },
  {
    id: "AY",
    firstName: "Ally",
    lastName: "Marshall",
    initials: "AY",
    rosterName: "Ally",
    role: "student",
    fte: "part",
    color: "#4a6a68",
    autoAssign: false,
    notes: "AUT student. Paired on PVT / c513. Not auto-assigned.",
    active: true,
  },
  {
    id: "SPM",
    firstName: "SPM",
    lastName: "",
    initials: "SPM",
    rosterName: "SPM",
    role: "pathologist",
    fte: "part",
    color: "#4a4a48",
    autoAssign: true,
    eveningOnly: true,
    notes: "EPP 1st-read initials on the historical rosters. Pathologist / senior reader — not a bench assignment.",
    active: true,
  },
  {
    id: "PATH",
    firstName: "Pathologist",
    lastName: "",
    initials: "PATH",
    rosterName: "Pathologist",
    role: "pathologist",
    fte: "part",
    color: "#5a5854",
    autoAssign: false,
    eveningOnly: true,
    notes: "Used when 2nd EPP read is a pathologist rather than a named scientist.",
    active: true,
  },
];

export function staffById(list: StaffMember[], id: string): StaffMember | undefined {
  return list.find((s) => s.id === id);
}

export function displayName(s: StaffMember): string {
  return s.lastName ? `${s.firstName} ${s.lastName}` : s.firstName;
}

export function rosterLabel(s: StaffMember, note?: string): string {
  return note ? `${s.rosterName} – ${note}` : s.rosterName;
}
